version:0.2

env:
    git-credential-helper: yes
phases:
  install:
     runtime-versions:
      java: corretto8
  pre-build:
    commands:
    - echo prebuild
    - git config credential.https://github.com/Smruthi01 Smruthi01 
    - git config credential.helper "$helper $options"
  build:
    commands:
    - echo build
    - mvn package
    - mvn spring-boot:run
  post-build:
    - echo post build
